elements/userlevel/fromnetmapdevice.cc
From @vlolteanu : 
If udev decides to rename an interface, 
_device->parent_nmd->nifp->ni_name will still contain the device's old 
name. This causes issues when FromNetmapDevice::initialize tries to look 
at /sys/class/net/$DEVICE/device/msi_irqs.
=> FromNetmapDevice: get interface name from element config

elements/userlevel/todpdkdevice.cc
=> Fixing retrieval of original mbuf in ToDPDKDevice.

userlevel/dpdk.mk
Signed-off-by: Georgios Katsikas <george.dit@gmail.com>
=> Fix for DPDK-based compilation when Mellanox PMD is set

elements/userlevel/monitoringreportsocket.cc, elements/userlevel/monitoringreportsocket.hh
This element acts as a UDP or TCP client that reports
a list of handlers' values and names to a remote UDP or TCP
server. Currently, this element is useful for element handlers
that contain arithmetic values (e.g., latency, throughput, etc).
The structure of each message is <timestamp, handler value, handler name>.
=> New socket element for monitoring purposes

elements/userlevel/monitoringreportsocket.cc, elements/userlevel/monitoringreportsocket.hh
The limitation in this commit is that click_max_cpu_ids
provides only the number of CPUs seen by Click, not the
total number of CPUs in the system. This could be improved
later
=> Ability to pin the monitoring socket on a core

elements/analysis/recordtimestamp.cc, elements/analysis/recordtimestamp.hh
This allows to use the desired element if more than one
are present in a Click configuration
=> RecordTimestamp takes numbered packets from input element

elements/analysis/timestampdiff.cc, elements/analysis/timestampdiff.hh
This patch contains re-worked statistics' calculation
methods, 2 bug fixes, and a new handler providing the last
latency value in the buffer.
One bug was related to the standard deviation calculation.
If variance was zero, then sqrt(0) was problematic.
The second bug was related to the min handler. If no
traffic is present, then this counter was MAX_UINT.
Now this is replaced by zero.
=> Updates and bug fixes in TimestampDiff

elements/analysis/checknumberpacket.cc, elements/analysis/checknumberpacket.hh, elements/analysis/numberpacket.cc, elements/analysis/numberpacket.hh, elements/analysis/recordtimestamp.cc, elements/analysis/recordtimestamp.hh, elements/analysis/timestampdiff.cc, elements/analysis/timestampdiff.hh, elements/userlevel/monitoringreportsocket.cc, include/click/atomic.hh, include/click/glue.hh
This patch extends the NumberPacket element to support network order
packet numbering and modifies this counter to a uint64_t integer to
support more scalable counting. The network order is configurable
by the user.
Since the NumberPacket element is used by other elements to perform
latency measurements, updates are performed to those elements as well.
Specifically:
* CheckNumberPacket has also support for network order
* RecordTimestamp can either be configured with network order or inherit
the settings of its own NumberPacket element
* TimestampDiff inherits the settings of its reference RecordTimestamp element
MonitoringReportSocket re-uses some static methods of the NumberPacket element
to perform host to network order conversions, instead of re-implementing the
same methods.
The …
=> Extensions in counting and timestamping elements

elements/analysis/timestampdiff.cc, elements/analysis/timestampdiff.hh, elements/userlevel/queuedevice.hh
This might occur when another element has been configured prior
to a queue device and attempts to call the thread_for_queue
function
=> Prevent potential access to unallocated memory in queue dev

elements/standard/ensureheadroom.cc, elements/standard/ensureheadroom.hh
`EnsureHeadroom(FORCE_SHRINK 1)` can be put after each element generating packets on slow path (`ICMPError`, ARP speakers) in order to explicitly remove headroom from a packet. That way, warnings about data move can be avoided in `ToNetmapDevice` for these packets. So, when such a warning occurs, it will be certain that it comes from some fast path packet.
=> Add FORCE_SHRINK parameter to the EnsureHeadroom element

elements/userlevel/fromdump.cc, elements/userlevel/fromdump.hh
This patch allows FromDump elements to generate packets from
pcap traces while being able to enforce a fixed frame size.
This configuration could be handy when you want to use the very
same Click code to generate either arbitrary frame sizes from a trace
or fixed frame sizes from the same trace.
Default behaviour is unchanged.
=> Allow FromDump to set a fixed frame size

elements/analysis/timestampdiff.cc, elements/analysis/timestampdiff.hh, elements/standard/delayunqueue.cc, test/analysis/latency-begin.testie
Allows to give an index from which the average/mean/max/... should be computed. This index is a packet number, maybe read using "index". By default, index is 0, the old behaviour.
This ultimately allows to display the change of latency over time.
=> TimestampDiff

include/click/timestamp.hh, lib/timestamp.cc, test/analysis/latency-begin.testie, userlevel/click.cc
Allows to change the amount of tick to warp in simtime mode
This allows to force us scale to enable some testing
=> click: Add --simtick options

test/userlevel/timewarp-01.testie
The timewrap test fails from time to time on travis, which is very slow.
The time to launch the process makes the delay longer than expected, so
let's relax the constraints.
In addition, substract from the real time the time it takes to launch an
empty click. This allows to be less error-proned regarding the time
a process takes to execute, eg on travis.
=> Timewarp test: relax constraint and more robust

include/click/packet.hh, lib/packet.cc
A little memory improvement. Ensure head of packet is on a boundary, and if using DPDK use the dpdk system for packet allocation.
Allows to simply use huge pages and cache alignment (mem is allocated on
boundary, and headroom is changed to be a multiple of cacheline size)
=> If using DPDK, allocate memory from DPDK mem

elements/userlevel/fromdump.cc, elements/userlevel/fromdump.hh, include/click/packet.hh, lib/packet.cc
This enhances the way parameter FORCE_LEN works.
When FORCE_LEN==-1, FromDump works as before.
When FORCE_LEN=x, where x in [MIN_MTU, MAX_MTU], each
frame is crafted with a fixed length x bytes.
When FORCE_LEN=0, each frame takes its original (actual)
length.
IP checksums are properly computed when needed.
=> FromDump reworked

lib/ip6address.cc
A malformed IP6Address, i.e. with more than 8 components, will cause the
memmove/memset at the end of parsing to fail.  This code is supposed to move
the post-:: bytes to the end of the address and zero out the bytes in the
center.  Instead, it moves some of the bytes the wrong way, potentially
writing prior to parts[] and then zeroing with a negative size.
Instead, make the parser stop when it hits 8 components and let parse figure
out that we did not consume the entire String.
Thanks: American Fuzzy Lop
Change-Id: I2966cb22fb5b44eb9e92dfc6a94e891cf5d02fa7
=> ip6address: fix parser array bounds issue/crash

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromnetmapdevice.cc, elements/userlevel/queuedevice.cc, elements/userlevel/queuedevice.hh, elements/userlevel/todpdkdevice.cc, elements/userlevel/tonetmapdevice.cc
If parallel, all available threads will open one queue of each device,
for better load balancing.
If shared (current default and behaviour), threads will be split among
devices, for better CPU locality.
=> From*Device: Add SCALE parameter

elements/userlevel/kerneltun.cc
This is a commit from kohler/click#397 rebased on FastClick element (after introduction of batching and multi-threading).
This commit adds flag IFF_NO_PI to tun/tap interface settings on Linux.
It flag changes frame format in order not to include protocol
information header. That is, with this flag, frames received/send from
tun/tap fd consist solely of raw underlying protocol (Ethernet/IP)
frames.
Protocol information header is not used by the element in any way, but
its presence adds a requirement for pulling packet data on receive and
pushing it before writing packet to the fd. Such a push becomes an
expensive push when there is is no enough headroom in packet, for
example when using native netmap buffers which do not have headroom.
Adding IFF_NO_PI flag eliminates the need for pulling …
=> KernelTun: Use IFF_NO_PI on Linux, remove LINUX_ETHERTAP mode

elements/userlevel/fromnetmapdevice.cc, elements/userlevel/fromnetmapdevice.hh, elements/userlevel/tonetmapdevice.cc, include/click/netmapdevice.hh, lib/netmapdevice.cc
Also change indentation in FromNetmapDevice to 4 spaces. The file contained mixed portions of tabs, spaces and tabs-with-spaces indentation. I find such an indentation mess very problematic, especially in files with convoluted logic like this. Maybe its high time to introduce consistent space-only indentation across the whole FastClick codebase?
=> Fix FromNetmapDevice timestamps and ToNetmapDevice arguments parsing

elements/userlevel/ensuredpdkbuffer.cc
This is a way to circumvent memory corruption when trying to ensure the buffer space of large DPDK frames
=> Conditional kill of packet in ensure DPDK buffer

userlevel/dpdk.mk
This patch allows FastClick to compile against DPDK 19.02-rc2.
More work might be needed for the final 19.02 release.
=> Towards DPDK 19.02

elements/standard/timedsource.cc
Timed source seg faults when Click is built with DPDK (appears to work without DPDK).  It appears the cause is attempting to create the "source packet" before the packet pool is ready.  Moving packet creation from Configure to Initialize (similar to other sources) solves the issue.
=> Timed source Segmentation Fault

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/queuedevice.cc, elements/userlevel/queuedevice.hh, include/click/dpdkdevice.hh, lib/dpdkdevice.cc
Adding support of VLAN offload features such as filtering of received VLAN packets and VLAN header stripping by hardware in received VLAN tagged packets.
This commit changes the default behavior and enables turning on/off these offloads, by adding two new boolean arguments to FromDPDKDevice element: VLAN_STRIP and VLAN_FILTER.
=> Enabling/disabling VLAN offload features in FromDPDKDevice

configure, configure.in, include/click/dpdkdevice.hh, userlevel/Makefile.in, userlevel/dpdk.mk
Also switch to meson when available. In the future DPDK plan to switch
to meson and we will use pkg-config to get dependencies.
This allows to remove the ugly code of dpdk.mk. It will be removed when
DPDK will fully move to meson.
Parallel development with Georgios Katsikas <katsikas.gp@gmail.com>
=> Support DPDK 19.05

lib/dpdkdevice.cc
VLAN offloading init moved after Rx queues' init
as it was causing segmentation fault, due to NULL
rxq object in mlx5_vlan_strip_queue_set().
=> VLAN offloading init moved

userlevel/dpdk.mk
dpdk v18.05 includes the octeontx family of libraries which get picked up by fastclick, but `librte_common_octeontx` is specifically gated by dpdk versions >= v18.09 which causes linker errors. this commit lowers the version gate to v18.05 to allow fastclick to link without error.
=> fix octeon dpdk make rules for v18.05

elements/userlevel/fromdpdkdevice.hh
=> Fix typo in documentation about DPDK

configure, configure.in, elements/analysis/recordtimestamp.hh, elements/analysis/timestampaccum.cc, elements/analysis/timestampaccum.hh, elements/analysis/timestampdiff.hh, elements/standard/pipeliner.cc, elements/standard/pipeliner.hh, elements/tunnel/erspandecap.cc, elements/userlevel/dpdkinfo.cc, elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh, elements/userlevel/linuxclock.cc, elements/userlevel/linuxclock.hh, elements/userlevel/queuedevice.cc, elements/userlevel/queuedevice.hh, elements/userlevel/tscclock.cc, elements/userlevel/tscclock.hh, include/click/dpdkdevice.hh, include/click/multithread.hh, include/click/packet.hh, include/click/timestamp.hh, lib/dpdkdevice.cc
This serie adds support for timestamp hardware offloading (when DPDK is patched, hopefully, they will accept my patch upstream). 
ConnectX5 NIC can write the device's internal Clock value (much like the TSC of x86 CPUs) to the packet timestamp field. From there TSCClock can be used to convert the clock ticks to real time.
Example : 
```
fd :: FromDPDKDevice($port, BURST 32, PROMISC true, VERBOSE 99, PAUSE none, 
MAXTHREADS 4, MTU $mtu, SCALE parallel, NUMA true, NUMA_NODE 1, TIMESTAMP true, 
NDESC 4096); 
-> tc :: TSCClock(INSTALL false, SOURCE fd, READY_CALL sl.run)  
-> ... // ToDump etc
sl :: Script(TYPE PASSIVE,                
wait 1s,                            
print "Now recording!"
write sact.switch 0 //To avoid writing packets with random timestamp, we have a Switch element to …
```
=> Series of patches for 100G Trace capture

include/clicknet/ip.h
The IP_OFFMASK macro is present in <netinet/ip.h>
thus user-level Click must refer to this macro
instead of redefining it.
=> Declare IP_OFFMASK macro only in kernel

elements/userlevel/dpdkdevclock.cc, elements/userlevel/dpdkdevclock.hh
This Clock will convert the timestamp of packets passing by from the
hardware timestamp to the current wall clock time using the new
rte_eth_read_clock API.
It inherits TSCClock, so it could be used (with INSTALL to true) to have the whole Click use the hardware as the unique source of time. It's probably a bad idea though, as reading the time through PCIe is slower than rdtsc.
=> DPDK device based clock

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/queuedevice.cc, elements/userlevel/queuedevice.hh, include/click/dpdkdevice.hh, lib/dpdkdevice.cc
To allow Rx jumbo frames offloading it is necessary
to set max_rx_pkt_len, which was not set by FastClick.
Also, fixed the initial VLAN filter and strip configuration
status (which was mistakenly set to true).
Messages are added to notify users about the status of
the offloading features when turned on.
=> LRO, Rx jumbo frames, and VLAN extend offloading

elements/analysis/averagebatchcounter.cc, elements/analysis/averagebatchcounter.hh
These statistics are related to the frame lengths being
observed either since the last tick or since the initialization
of this element. An input parameter defines whether these extra
statistics will be provided or not. Also, the element's documentation
is improved.
=> Additional statistics for AverageBatchCounter

userlevel/dpdk.mk
This patch helps to compile FastClick against 19.11-rc1.
Apart from changes introduced in 19.11, additional changes
are introduced to cover previous versions (mostly 19.08).
More patches to follow until final 19.11.
=> Towards DPDK 19.11

.travis.yml, elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh, elements/userlevel/metron.hh, elements/userlevel/queuedevice.cc, elements/userlevel/todpdkdevice.cc, elements/userlevel/todpdkdevice.hh, include/click/dpdkdevice.hh, include/click/flowdirector.hh, lib/dpdkdevice.cc, lib/flowdirector.cc, userlevel/dpdk.mk
New configuration parameters FLOW_DIR_ISOLATE in FromDPDKDevice.
If set != 0, this parameter guarantees that all ingress traffic
comes from defined flow rules only (current and future), thus
rendering PMD more deterministic. It can be configured only if the
device is in MODE flow_dir. Handlers are added in FromDPDKDevice to
read the current value of this parameter and reset it at will.
Fixed bug in FromDPDKDevice queue_count and queue_bytes handlers.
Impoved the documentation of FromDPDKDevice and ToDPDKDevice elements
by adding description for all configuration parameters and handlers.
Some parameters mentioned in FromDPDKDevice element belong to ToDPDKDevice,
therefore they are moved accordingly.
FlowDirector supports flow isolation through the abovementioned
FromDPDKDevice handler. …
=> Metron extensions and bug fixes

elements/userlevel/metron.cc, elements/userlevel/metron.hh, include/click/flowdirector.hh, lib/flowdirector.cc, lib/metron/servicechain.cc
The current stack allocation of flow rule IDs
limits the ability to store huge batches of rules.
As some NICs (e.g., Mellanox) allow to store millions
of rules, we updated the process of adding rules from
file, to scale the number of istalled rules to several
millions.
Documentation updates and refactoring are also performed.
=> Ability to load millions of flow rules

elements/ethernet/arpadvertiser.cc, elements/ethernet/arpadvertiser.hh
Input element that generates periodic ARP
responses to designated nodes.
It uses an internal ARP table which can be
populated with entries through a write handler.
Write handlers are also available for deletion
and cleaning of the ARP table.
This element is also batch compatible.
=> New ARPAdvertiser element

config-userlevel.h.in, config.h.in, configure, configure.in, include/click/ewma.hh, include/click/router.hh, include/click/routerthread.hh, lib/router.cc, lib/routerthread.cc
By counting a proportion of useful cycles over all cycles spent in each
routerthreads. Then it is accessible through the load handler.
This allows to have a notion of load under polling with DPDK.
However it only works when context switching is very low/ each thread is assigned to a single core.
=> Load tracking: Allows to compute the load of each thread

elements/ethernet/arpquerier.cc, elements/ethernet/arpquerier.hh, elements/test/hashtablemptest.cc, elements/test/hashtablemptest.hh, include/click/hashtablemp.hh, test/standard/hashtablemp-01.testie
A huge problem to solve in Click that stayed there way too long...
Concurrent access through ARPQuerier use synchronized access to a common table. (A
spinlock!!!). So we keep a per-core cache, which supports exhaustion
using the new AgeingTable. Makes things much much more faster ;)
Also this is the first use of the AgeingTable(MP is also available), that transparently implements lazy ageing.
=> ARPQuerier: Add a per-core cache

elements/flow/flowipmanager.cc
Add LF mode to FlowIPManagerMP to add lock-free concurrency mode.
In practice it is done in FlowIPManager, as FlowIPMangerMP has no configuration.
=> FlowIPManager: Add LF mode

include/click/dpdkdevice.hh, lib/dpdkdevice.cc
An issue before this patch was that rte_eth_dev_configure
was invoked before the offloading capabilites were set.
Now, all the configuration is applied and rte_eth_dev_start
is moved at the end of the initialize_device method.
=> Reworked initialize_device()

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/queuedevice.cc, elements/userlevel/queuedevice.hh, include/click/dpdkdevice.hh, lib/dpdkdevice.cc
* LRO and JUMBO params are now integers
* With value=0, both features are disabled
* With value=1, each feature gets a default value (9000 bytes)
* with value>1, each feature is configurable in [64, 65536]
=> Fully-functional LRO and Jumbo

mininet/README.md, mininet/Vagrantfile, mininet/switch/topology-mininetonly.py, mininet/switch/topology.py
For now just a switch but I'd like to add a router.
In the mininet folder one can simply run "vagrant up" to launch a VM with fastclick and mininet configured.
Then, inside the VM one can run one of the provided mininet topologies that will run Click on one host to run the functionality, and try it out with the mininet CLI. Hopefully this will be useful for learning purposes, and to write repeatable (functional) experiments in the future.
=> Add mininet/Vagrant examples

.travis.yml, aclocal.m4, config.h.in, configure, configure.in, elements/standard/paint2.cc, elements/standard/paint2.hh, elements/standard/search.cc, elements/standard/search.hh, elements/standard/unstripanno.cc, elements/standard/unstripanno.hh, elements/tcpudp/striptcpheader.cc, elements/tcpudp/striptcpheader.hh, elements/tcpudp/unstriptcpheader.cc, elements/tcpudp/unstriptcpheader.hh, elements/test/stringtest.cc, include/click/packet_anno.hh, include/click/string.hh, lib/nameinfo.cc, lib/string.cc, test/standard/search-01.testie, test/standard/string-01.testie, test/tcpudp/StripTCPHeader-01.testie
Add the Search element that searchs for a pattern in the packet, using AVX2 if available. Hence all the importance of AVX2.
At the same time I think we should have -march=native by default (it was probably already added by DPDK anyway). One can disable it with --enable-portable-binary.
=> Use march=native by default, and check for AVX2

README.md, conf/metron/metron-dispatcher-flow-legacy-af-pkt.click, conf/metron/metron-dispatcher-flow-legacy-af-xdp.click, conf/metron/metron-dispatcher-flow.click, elements/test/stringtest.cc, elements/userlevel/fromdpdkdevice.hh, elements/userlevel/metron.cc, elements/userlevel/metron.hh, elements/userlevel/queuedevice.hh, include/click/flowdispatcher.hh, include/click/string.hh, lib/dpdkdevice.cc, lib/flowdispatcher.cc, lib/metron/servicechain.cc, lib/string.cc, userlevel/dpdk.mk
This upgrade follows a pull request to ONOS for the
control plane part of Metron, including:
* Refactored REST API with consistent resource names
* Extended REST API with more management operations
* Time exchange between Metron server and ONOS
* Controller-driven NIC port configuration
* NIC table statistics' report to ONOS
* NIC queue descriptions' report to ONOS
* Server connect/disconnect operations driven by ONOS
* Additional system statisticss (CPU caches and memory)
* Click's string library extended
* Fixed deprecated naming conventions (e.g., Flow Director)
* Metron example configurations updated
* Metron documentation updated
=> Major Metron upgrade

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh
I saw this way of doing things in multiple elements. Seems better to avoid names that could clash between inherited instances etc.
=> FromDPDKDevice: avoid global enum definition

configure, configure.in
With a global DPDK installation, the configure script showed an error
after the detection instead of "yes" and the check for read_clock
support was never run against the global DPDK.
=> Improve handling of global DPDK in configure

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh, elements/userlevel/todpdkdevice.cc, elements/userlevel/todpdkdevice.hh
This allows to activate UDP checksum offloading for ToDPDKDevice, and allows to activate IP, TCP and UDP checksum offloading for FromDPDKDevice.
=> Checksum offloading for TX (UDP) and RX (IP, TCP, UDP) with DPDK

elements/analysis/cyclecountaccum.cc, elements/flow/flowipmanagerimp.cc, elements/flow/flowipmanagerimp.hh, elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh, include/click/flowrulemanager.hh, lib/flowrulemanager.cc
- Fix handlers for counters in FromDPDKDevice
- Fix count handler in FlowIPManagerIMP, now it returns the total number of flows
- Add `verbose` to FlowRuleManager to allow silent operations
- Solve division by zero error in CyccleCountAccum when packet count is 0
=> Minor fixes and improvements

.travis.yml, configure, configure.in, elements/research/ddiotune.cc, elements/research/ddiotune.hh
Least supported version becomes 16.11 LTS. Solves the travis bug and makes more sense.
=> Bump minimal supported DPDK version to oldest LTS

.gitignore, Makefile.in, config-userlevel.h.in, configure, elements/standard/rrswitch.cc, elements/standard/threadsafequeue.cc, elements/test/atomic.cc, elements/test/atomic.hh, include/click/atomic.hh, include/click/glue.hh, include/click/multithread.hh, include/click/notifier.hh, include/click/routerthread.hh, include/click/standard/storage.hh, lib/router.cc, lib/routerthread.cc, lib/string.cc
- Add support for C++11 atomic types, which could be enabled with `--enable-atomic-builtins`.
- TSC counter for all DPDK supported platforms
- Minor additions to `.gitignore`
=> Atomics variables

aclocal.m4, configure, configure.in
Fix missing `configure.in` file. The handling of the flag has been fixed too.
This is a fix for https://github.com/tbarbette/fastclick/pull/276#issuecomment-735239966
=> builtin atomics: fix missing configure.in file

elements/userlevel/fromdpdkdevice.cc, elements/userlevel/fromdpdkdevice.hh, elements/userlevel/todpdkdevice.cc, include/click/packet.hh, include/click/packetbatch.hh, lib/packet.cc, lib/packetbatch.cc
The user may do the liveness analysis on its own, in anycase things like
aggregate, paint etc should be set before being read
This change was made as part of PacketMill
=> Packet annotation: allow not to clear them

config-userlevel.h.in, config.h.in, configure, configure.in, elements/ethernet/ethermirror.cc, elements/userlevel/todpdkdevice.cc, elements/userlevel/todpdkdevice.hh, include/click/dpdkdevice.hh, include/click/packet.hh, include/click/packetbatch.hh, lib/packet.cc
Disable packet cloning, preventing running packet accross multiple parallel pipelines, which is something not usually needed.
Disable the TX buffering queue for DPDK
=> New options to disable features

elements/analysis/averagebatchcounter.cc, elements/analysis/frommindump.cc, elements/analysis/multireplay.cc, elements/analysis/replay.cc, elements/analysis/replay.hh, elements/ethernet/ethervlanencap.cc, elements/flow/flowcounter.cc, elements/flow/tcpreorder.cc, elements/ip/ipaddrpairrewriter.cc, elements/ip/ipaddrrewriter.cc, elements/ip/iproutetable.cc, elements/standard/infinitesource.cc, elements/standard/mixedqueue.cc, elements/standard/paint.cc, elements/standard/pipeliner.cc, elements/standard/rrswitch.cc, elements/standard/strip.cc, elements/tunnel/gtplookup.cc, elements/userlevel/todpdkdevice.cc, elements/userlevel/todpdkring.cc, include/click/packetbatch.hh, lib/packetbatch.cc, lib/router.cc
Towards allowing batches to be either vector, LL or whatever we have to
stop casting PacketBatch to the first packet, as vectors would be
independent objects
=> PacketBatch: Remove inheritance to make the batching method abstract

lib/dpdkdevice.cc
unset option for PAUSE was specified in the documentation but not
accepted by the parser
=> FromDPDKDevice: add unset option to PAUSE

configure, configure.in, include/click/glue.hh
- When checking for AVX2 support on non x86 platform the control is skipped, otherwise it fails the configuration. Should this control be implemented differently?
- Fix a wrong compilation flag guard regarding click_get_cycles
=> Fix compilation on non x86

elements/tcpudp/settcpchecksumip6.cc, elements/tcpudp/settcpchecksumip6.hh
The existing `SetTCPChecksum` element only supports TCP over IPv4. This is a new element that does the same for TCP over IPv6.
The new element's naming convention follows `FastUDPSource` and `FastUDPSourceIP6`, and is also the reason I've put this in `tcpudp/` instead of `ip6/`.
The code is based mostly on the original `SetTCPChecksum` and the way `FastUDPSourceIP6` calculates checksum for its packets.
=> New element: SetTCPChecksumIP6 - Calculates TCP/IPv6 checksum and sets the TCP header field.

elements/userlevel/devicebalancer.cc
Add DPDK dependency to DeviceBalancer because it requires `rte_flow.h` which is only available with DPDK. This modification repairs the build of fastclick without DPDK.
=> [Fix build without DPDK] Add DPDK dependency to DeviceBalancer

config-linuxmodule.h.in, config-userlevel.h.in, configure.in, include/click/hashallocator.hh
Pick-up a PR from mainline at https://github.com/kohler/click/pull/366
When the Click build is configured with the option --enable-hash-allocator-poisoning, this change will cause the HashAllocator to write a "poison" byte value to the block being returned to a HashAllocator pool.  This ensures that when a stale reference to a freed block is followed, the code will be much less likely to interpret the block as a valid object or struct.  In particular, pointer values will be non-NULL but bad, leading to immediate failure with a clear signature indicating the presence of a stale reference bug.
=> (PR from mainline) HashAllocator: poison freed blocks

elements/ip/checkipheader.cc
The argument is currently parsed twice. The first time it's consumed, the second time it's always set to 0.
=> Fix parsing of CheckIPHeader offset argument

elements/standard/bandwidthmeter.cc, elements/standard/bandwidthmeter.hh, elements/standard/ratedsource.cc, elements/standard/ratedunqueue.cc, include/click/ewma.hh
This adds some uint32->uint64 conversions which I missed in #395.
They affect RatedUnqueue, RatedSource and BandwidthMeter.
=> Fixes for 64-bit rates

elements/standard/ratedunqueue.cc, test/standard/BandwidthRatedSplitter-01.clicktest, test/standard/BandwidthRatedUnqueue-01.clicktest
Reading 32 packets will lead to very large imprecision in term of byts
=> Set BURST to 1 by default for bandwidthratedunqueue

userlevel/Makefile.in
=> Fix clp not being included for Packetmill when using the --disable-test option

include/click/element.hh
Due to a misplaced }, compilation fails when FastClick is configured with statistics set to 2. 
This fixes #409.
=> Fix compilation with --enable-stats=2

elements/userlevel/controlsocket.cc, elements/userlevel/httpserver.cc, lib/router.cc
- Added 'MHD_OPTION_LISTENING_ADDRESS_REUSE' to allow the reuse of the listening address for the HTTPserver.
- replace 'SO_REUSEADD' with 'SO_REUSEPORT' in ControlSocket to allow reuse of the same port.
=> Refactor ControlSocket & HttpServer elements

elements/userlevel/httpserver.cc
I forgot to re-add  'MHD_OPTION_END'.
It is mandatory to use MHD_OPTION_END as last argument, even when there are no additional arguments.
=> fix httpserver.cc

lib/router.cc
Make elementmap.xml path resolution dynamic by using CLICK_DATADIR variable
=> Make elementmap.xml path resolution dynamic
