- elements/standard/markmacheader.cc
- elements/standard/markmacheader.hh
> MarkMACHeader: now a BatchElement

- elements/userlevel/todpdkdevice.cc
> Added missing timer-thread mapping in ToDPDKDevice

- elements/ethernet/arpresponder.cc
- elements/ethernet/arpresponder.hh
- elements/ethernet/storeetheraddress.cc
- elements/ethernet/storeetheraddress.hh
- elements/icmp/checkicmpheader.cc
- elements/icmp/checkicmpheader.hh
- elements/icmp/icmperror.cc
- elements/icmp/icmperror.hh
- elements/ip/ipprint.cc
- elements/ip/ipprint.hh
- elements/ip/markipheader.cc
- elements/ip/markipheader.hh
- elements/ip/stripipheader.cc
- elements/ip/stripipheader.hh
- elements/ip/unstripipheader.cc
- elements/ip/unstripipheader.hh
Please review my modifications and feel free to accept or reject them :)
> Batching support for some elements

- elements/userlevel/fromnetmapdevice.cc
The code is not working properly if QUEUE != 0.
> Fix QUEUE/N_QUEUE bug

- elements/tcpudp/fastudpflows.cc
- elements/tcpudp/fastudpflows.hh
If you approve this, I can also push a similar patch for TCP and UDPv6
> Batching support for FastUDPFlows

- elements/userlevel/fromdpdkring.hh
- elements/userlevel/todpdkring.cc
- elements/userlevel/todpdkring.hh
This patch now makes the style of From/ToDPDKRing elements consistent.
> Converted tabs to spaces for ToDPDKRing and FromDPDKRing.hh

- INSTALL.md
- configure
- configure.in
- m4/click.m4
- userlevel/click.cc
DPDK does not belong to Intel any more
>  Replaced Intel DPDK with DPDK

- elements/analysis/numberpacket.cc
- elements/analysis/numberpacket.hh
- elements/analysis/recordtimestamp.cc
- elements/analysis/timestampdiff.cc
- elements/analysis/timestampdiff.hh
> Some improvements in various latency analysis elements

- elements/standard/dropbroadcasts.cc
- elements/standard/dropbroadcasts.hh
> Batching support for DropBroadcasts

- elements/ip/iprewriterbase.cc
- elements/ip/iprewriterbase.hh
This fixes some (hopefully all?) MT issues of these elements
> Updated IPRewriters' base from Metron

- elements/analysis/checknumberpacket.cc
- elements/analysis/checknumberpacket.hh
> Bumped the size of the counter in CheckNumberPacket

- elements/userlevel/monitoringreportsocket.cc
> Improved stdout and stderr of MonitoringReportSocket

- elements/analysis/timestampdiff.cc
> Prevent division with zero in TimestampDiff average handler

- elements/tcpudp/udpip6encap.cc
- elements/tcpudp/udpip6encap.hh
DPDK Batch support for UDPIP6Encap
> DPDK Batch support for UDPIP6Encap

- lib/router.cc
> Static initialize DPDK only if enabled

- conf/dpdk/dpdk-primary.click
- conf/dpdk/dpdk-secondary.click
> Updated DPDK ring configuration example

- elements/analysis/numberpacket.hh
- elements/analysis/recordtimestamp.cc
- elements/analysis/timestampdiff.cc
- elements/analysis/timestampdiff.hh
- elements/userlevel/monitoringreportsocket.cc
- elements/userlevel/monitoringreportsocket.hh
> Fixed documentation issues in timestamping elements

- elements/analysis/recordtimestamp.cc
- elements/analysis/recordtimestamp.hh
This patch gives a slight performance boost
> Inline method in RecordTimestamp's fast path

- elements/analysis/timestampdiff.cc
- elements/analysis/timestampdiff.hh
User can select to supress warnings about delayed packets.
Default behaviour remains as before
k
> Do not print delayed packets if requested

- include/click/hashtable.hh
> Fixed typos in HashTable docs

- elements/userlevel/fromdpdkdevice.cc
- elements/userlevel/fromdpdkdevice.hh
- elements/userlevel/todpdkdevice.cc
- include/click/dpdkdevice.hh
- lib/dpdkdevice.cc
And also a few type correction to avoid warnings.
> Parameter for DPDK pause frame mode

- .travis.yml
This should finally fix the "illegal instructions" false positive on travis
DPDK is build (correctly this time) with no fancy instruction set.
> DPDK : Fix false positive because of illegal instructions

- elements/standard/paintrr.cc
- elements/standard/paintrr.hh
- include/click/batchelement.hh
- test/standard/PaintRR-01.testie
3 helper element to easily build batch-compatible without downgrading performances. The explanation is actually already in the wiki : https://github.com/tbarbette/fastclick/wiki/Batching
And then PaintRR which uses one of them.
> Batching helpers

- elements/userlevel/fromdpdkdevice.cc
Also, some style fixes to comply with space-based
tabs of 4 characters
> Fix return value of xstats handler

- elements/ethernet/ethervlanencap.cc
- elements/ethernet/ethervlanencap.hh
- elements/ethernet/setvlananno.cc
- elements/ethernet/setvlananno.hh
- elements/ethernet/stripethervlanheader.cc
- elements/ethernet/stripethervlanheader.hh
- elements/ethernet/vlandecap.cc
- elements/ethernet/vlandecap.hh
- elements/ethernet/vlanencap.cc
- elements/ethernet/vlanencap.hh
> Batching support for VLAN elements

- elements/ethernet/ensureether.cc
- elements/ethernet/ensureether.hh
> Batching support for EnsureEther

- elements/ethernet/etherencap.cc
Batching is done using the helpers and not the old-style way
> EtherEncap batching helper

- elements/standard/infinitesource.hh
- elements/standard/ratedsource.cc
- elements/standard/ratedsource.hh
Also description update for InfiniteSource
> Configurable headroom for RatedSource

- elements/test/functiontest.cc
- include/click/tinyexpr.hh
- test/handlers/privatehandler-01.testie
Travis is failing because it uses an old compiler. Still, I'm going to fix this...
> Try to make old compilers happy

- lib/string.cc
> String split returns empty vector when no input

- elements/test/stringtest.cc
- elements/test/stringtest.hh
- lib/string.cc
- test/userlevel/string-01.testie
Not very complete but brings up case discussed on the issues
> String test suite

- elements/userlevel/fromdevice.cc
- elements/userlevel/fromdevice.hh
- elements/userlevel/todevice.cc
- elements/userlevel/todevice.hh
I have done it mostly to avoid batch mode warnings on startup and did not expect performance gains. Nevertheless, I observe 8-10% higher throughput with batching.
> Batching in FromDevice.u and ToDevice.u elements

- elements/standard/bwratedunqueue.cc
- elements/standard/ratedunqueue.cc
- elements/standard/ratedunqueue.hh
Allows to specify batch size in pull mode
> RatedUnqueue : BURST argument

- elements/standard/tee.cc
- elements/standard/tee.hh
And add the override flag that would have catched this issue...
> PullTee: Fix bad signature

- elements/grid/gridprobereplyreceiver.cc
> Bypass deprecated function call in gridprobereplyreceiver

- elements/userlevel/counterfile.cc
> Handle ftruncate error during CounterFile initialization

- aclocal.m4
- config.h.in
- configure
- configure.in
- elements/threads/balancedthreadsched.cc
- elements/tunnel/erspandecap.cc
- include/click/glue.hh
- include/click/hashtablemp.hh
- include/click/ipaddress.hh
- include/click/iphelper.hh
- include/click/packetbatch.hh
- include/click/task.hh
- include/click/tcphelper.hh
- include/clicknet/tcp.h
- lib/routerthread.cc
- lib/tcphelper.cc
- m4/ax_check_compile_flag.m4
- userlevel/Makefile.in
Mostly things taken from recent development branches, such as MiddleClick
> Various updates

- .travis.yml
- elements/userlevel/fromdpdkdevice.cc
- include/click/tcphelper.hh
- lib/dpdkdevice.cc
- userlevel/dpdk.mk
This patch supports up to DPDK 19.08-rc2.
More work migth be needed towards 19.08.
> Preliminary support for DPDK 19.08

- elements/wifi/linktable.hh
> IPPair unnecessarily re-defined in LinkTable

- elements/userlevel/fromdpdkdevice.cc
- include/click/dpdkdevice.hh
- lib/dpdkdevice.cc
> Fixed compatibility issue with DPDK 19.08

- elements/userlevel/fromdpdkdevice.cc
- include/click/dpdkdevice.hh
- include/click/tcphelper.hh
- lib/dpdkdevice.cc
I had this fix in RSS++ branch. I think this is cleaner, no?
> DPDK smaller fix for 19.08

- elements/analysis/aggregatelen.cc
- elements/analysis/aggregatelen.hh
> Batching support for AggregateLength element

- elements/standard/discardnofreebuffer.cc
- elements/standard/discardnofreebuffer.hh
- elements/tcpudp/checktcpheader.cc
- elements/tcpudp/checktcpheader.hh
- elements/tcpudp/checkudpheader.cc
- elements/tcpudp/checkudpheader.hh
- elements/tcpudp/striptransportheader.cc
- elements/tcpudp/striptransportheader.hh
- elements/tcpudp/unstriptransportheader.cc
- elements/tcpudp/unstriptransportheader.hh
> Various commits

- elements/analysis/averagebatchcounter.cc
- elements/analysis/averagebatchcounter.hh
> Fixed counter and handlers in AverageBatchCounter

- include/click/packet.hh
- include/click/userutils.hh
- lib/userutils.cc
Also, a typo is fixed in packet.hh
> Some user utils added for quick debugging

- elements/ip/ipfilter.cc
- elements/ip/ipfilter.hh
- elements/standard/classification.cc
To see the actual changes introduced by caching, please check the first commit only.
The efficiency of the caching could be further improved if we use the RSS hash directly from the hardware, but this is left as future work :p
> IPFilter caching and style changes

- elements/standard/averagecounter.cc
- elements/standard/averagecounter.hh
- elements/userlevel/dpdkinfo.cc
- elements/userlevel/fromdpdkdevice.cc
- elements/userlevel/queuedevice.cc
- elements/userlevel/queuedevice.hh
- include/click/glue.hh
- include/click/ipaddress.hh
- include/click/vector.cc
- include/click/vector.hh
- lib/dpdkdevice.cc
Hi all,
After solving a huge source of cache miss in DPDK TX, I thought it would be nice to version a bit FastClick, in a not too formal way so we could reference the version when need be.
So I propose to merge v1911 in a few days, and then create a tag. But I'm open to suggestions.
Tom
> FastClick v19.11

- .travis.yml
Remove 2.2.0 that has problem with the recent Travis bionic image.
> Merge mainline Click

- elements/ip/ipprint.cc
- elements/ip/ipprint.hh
> IPPrint option to print VLAN ID

- configure
Shows whether HTTP daemon or JSON libraries are
available
> Extra packages' verbosity in configure

- elements/ip/ipprint.cc
- elements/ip/ipprint.hh
- elements/ip6/ip6print.cc
- elements/ip6/ip6print.hh
Also, style changes for IP6Print and IPPrint
and documentation for IP6Print
> Batching support and active param for IP6Print

- elements/ethernet/arpfaker.cc
- elements/ethernet/arpfaker.hh
- elements/ethernet/etherpausesource.cc
- elements/ethernet/etherpausesource.hh
- elements/ethernet/getetheraddress.hh
- elements/ethernet/hostetherfilter.cc
- elements/ethernet/hostetherfilter.hh
- elements/ethernet/ip6ndadvertiser.hh
- elements/ethernet/setetheraddress.hh
> Batch compatibility for 6 Ethernet elements

- configure
- configure.in
> Display message about batching in configure

- elements/flow/flowipmanagerimp.cc
- elements/flow/flowipmanagerimp.hh
- elements/research/flowipmanagerhmp.cc
- elements/research/flowipmanagerhmp.hh
These dependencies manifest themselves when DPDK is not present
> Fixed flow elements' dependencies

- elements/flow/batchfcb.hh
- elements/flow/flowhyperscan.cc
- elements/flow/flowhyperscan.hh
- elements/flow/flowiploadbalancer.cc
- elements/flow/flowiploadbalancer.hh
- elements/flow/flowipmanager.cc
- elements/flow/flowipmanager.hh
- elements/flow/flowipmanagerimp.cc
- elements/flow/flowipmanagerimp.hh
- elements/flow/flowipmanagermp.cc
- elements/flow/flowipmanagermp.hh
- elements/flow/flowipnat.cc
- elements/flow/flowipnat.hh
- elements/flow/flowlock.cc
- elements/flow/flowlock.hh
- elements/research/countertest.cc
- elements/research/countertest.hh
- elements/research/extendedcounters.cc
- elements/research/extendedcounters.hh
- elements/research/flowipmanagerhmp.cc
- elements/research/flowipmanagerhmp.hh
- elements/research/flowipmanagerspinlock.cc
- elements/research/flowipmanagerspinlock.hh
- elements/research/workpackage.cc
- elements/research/workpackage.hh
- include/click/timerwheel.hh
- lib/flowelement.cc
Based on the previous pull request ()
> Style changes in flow & research packages

- elements/flow/flowipmanager.cc
- elements/research/workpackage.hh
A small error in handler name and documentation
> Small updates

- .travis.yml
There is a certain number of false positive in Click regression tests,
so let travis retry a few times
> travis: Retry make check automatically

- include/click/glue.hh
* Added proper DPDK compatibility
> Fixed method for computing cycles

- userlevel/dpdk.mk
Compliance with DPDK 20.02-rc1
> Towards DPDK 20.02

- .travis.yml
- configure
- configure.in
- doc/click-elem2man
- elements/analysis/cyclecountaccum.cc
- elements/flow/batchfcb.hh
- elements/flow/flowipmanager.cc
- elements/flow/flowipmanagerimp.cc
- elements/flow/flowipnat.cc
- elements/research/countertest.cc
- elements/research/countertest.hh
- elements/research/flowipmanagerhmp.cc
- elements/research/flowipmanagerhmp.hh
- elements/userlevel/httpserver.cc
- include/click/algorithm.hh
- include/click/ring.hh
- include/click/timerwheel.hh
- test/flow/flowipnat-01.testie
Also compile flow and research packages, which catched a few bugs when batching is disabled, etc.
> Update travis to do more tests

- elements/analysis/batchstats.hh
- elements/analysis/burststats.cc
- elements/analysis/burststats.hh
- include/click/statvector.hh
Use the code from BatchStats into a common library to implement
a vector to keep track of frequency of occurences, and generate
common handlers on that
> BurstStats: Add burst-statistic

- elements/standard/script.cc
- elements/standard/script.hh
- test/standard/Script-04.testie
Somehow I forgot this branch :p
> New script handlers

- configure
- configure.in
- elements/research/ddiotune.cc
- elements/research/ddiotune.hh
DDIOTune element can enable/disable DDIO and change the number of IIO LLC ways. Besides, it can print some info about the cache hierarchy. Let me know if I need to change anything.
> DDIOTune element added

- elements/userlevel/fromdpdkdevice.cc
- elements/userlevel/fromdpdkdevice.hh
- elements/userlevel/queuedevice.cc
- elements/userlevel/queuedevice.hh
Remove load tracking, that is done with --enable-cpu-load
Put everything interrupt related under a #ifdef, as it is yet not tested
> FromDPDKDevice: Cleanup

- userlevel/dpdk.mk
* v20.05-rc1
* v20.05-rc2
* v20.05-rc3
* v20.05-rc4
> DPDK 20.05 support

- elements/tcpudp/fasttcpflows.cc
- elements/tcpudp/fasttcpflows.hh
- elements/tcpudp/fastudpflows.cc
- elements/tcpudp/fastudpflows.hh
> Style changes to FastTCP/UDPFlows

- conf/rule-gen/gen-dpdk-flow-rules.click
- conf/rule-gen/gen-ipfilter-rules.click
- conf/rule-gen/gen-iplookup-rules.click
- conf/rule-gen/gen-openflow-rules.click
- elements/ip/generateipdpdkflowrules.cc
- elements/ip/generateipdpdkflowrules.hh
- elements/ip/generateipfilter.cc
- elements/ip/generateipfilter.hh
- elements/ip/generateipfilterrules.cc
- elements/ip/generateipfilterrules.hh
- elements/ip/generateipflowdispatcher.cc
- elements/ip/generateipflowdispatcher.hh
- elements/ip/generateiplookup.cc
- elements/ip/generateiplookup.hh
- elements/ip/generateiplookuprules.cc
- elements/ip/generateiplookuprules.hh
- elements/ip/generateipopenflowrules.cc
- elements/ip/generateipopenflowrules.hh
- include/click/ipaddress.hh
- include/click/ipflowid.hh
* Object-oriented design
* New OpenFlow rule generator element
* Bug fixes related to generated port numbers
* New example configurations
> Reworked rule generators

- elements/standard/rrmultisched.cc
- elements/standard/rrmultisched.hh
- elements/standard/rrsched.cc
- elements/standard/rrsched.hh
> Batching support for RR sched elements

- configure
- configure.in
- elements/ip/flowminloadswitch.cc
- elements/ip/flowminloadswitch.hh
- elements/ip/flowrrswitch.cc
- elements/ip/flowrrswitch.hh
- elements/research/flowrandload.cc
- elements/research/flowrandload.hh
- elements/research/randload.cc
- elements/research/randload.hh
- elements/standard/exactcpuswitch.cc
- elements/standard/exactcpuswitch.hh
- test/threads/threadvector-cpuswitch.testie
- test/threads/threadvector-exactcpuswitch.testie
Most from Metron and RSS++
Not ready yet, just to not forget
> Set of elements from research projects

- elements/flow/flowiploadbalancer.cc
- elements/flow/flowiploadbalancer.hh
- elements/flow/flowswitch.cc
- elements/flow/flowswitch.hh
- elements/tcpudp/iploadbalancer.cc
- elements/tcpudp/iploadbalancer.hh
- elements/userlevel/fromdevice.cc
- elements/userlevel/rawsocket.cc
- include/click/loadbalancer.hh
Taken from RSS++. Support for power of 2, least loaded, tracking various
metrics, auto weighted round robin, more hash and constant hashing.
> LoadBalancer: Add additional techniques

- userlevel/dpdk.mk
* v20.08-rc1
* v20.08-rc2
* v20.08-rc3
* v20.08-rc4
> Support for DPDK 20.08

- elements/flow/flowiploadbalancer.cc
- elements/flow/flowiploadbalancer.hh
- elements/flow/flowipnat.cc
- elements/flow/flowipnat.hh
- elements/flow/flowlock.cc
- elements/flow/flowlock.hh
- elements/flow/flowswitch.cc
- elements/flow/flowswitch.hh
- elements/research/flowrandload.cc
- elements/research/flowrandload.hh
- elements/test/testflowspace.cc
- elements/test/testflowspace.hh
- include/click/flow/flowelement.hh
- lib/flowelement.cc
First, use push_flow instead of push_batch in flow elements, as the header is different and those elements indeed receive batches of the same flow.
Also flow elements should use solve_initialize only, because in general they need to wait for the offset and FlowManager to have passed
> flow: Use push_flow

- .travis.yml
- config.h.in
- configure
- configure.in
- elements/userlevel/fromdpdkdevice.cc
- include/click/dpdkdevice.hh
- include/click/element.hh
- include/click/flowruleparser.hh
- include/click/iphelper.hh
- lib/dpdkdevice.cc
- test/analysis/latency-01.testie
- test/analysis/latency-02.testie
- userlevel/Makefile.in
Also add travis support. For now travis produce a problem with clang.
However it's not reproducible locally. I'll verify with the next build
if it still appears. It is in the exclude list for now.
> Fix Meson/system build and warning

- configure
- configure.in
- userlevel/Makefile.in
- userlevel/rte_parse.mk
Covers both meson and make build systems
> Fixed DPDK configuration

- .github/workflows/ci.yml
- .gitlab-ci.yml
- .travis.yml
- README.md
- configure
- configure.in
- elements/test/atomic.cc
- test/flow/flowipnat-01.clicktest
- test/standard/StoreData-01.clicktest
- test/userlevel/dpdk.clicktest
This is mainly a test to trigger a verification
> Update Github Actions

- config-userlevel.h.in
- elements/analysis/fromipsumdump.cc
- elements/standard/discardnofreebuffer.cc
- elements/tcpudp/resetipchecksum.cc
- elements/userlevel/fromdpdkdevice.cc
- elements/userlevel/fromdpdkdevice.hh
- include/click/dpdk_glue.hh
- include/click/dpdkdevice.hh
- include/click/fromfile.hh
- include/click/packet.hh
- lib/dpdkdevice.cc
- lib/fromfile.cc
Mostly changes from PacketMill
> Fix --enable-dpdk-packet

- DISTFILES
- config-userlevel.h.in
- configure
- configure.in
- include/click/llvmutils.hh
- lib/llvmutils.cc
- userlevel/Makefile.in
- userlevel/packetmill.cc
@tbarbette Can you check this?
I still need to add some checks, but this is the basic version. I could still do the click-llvm-opt or separate some parts if you think it is necessary.
> integrating LLVM passes to packetmill.cc

- config-userlevel.h.in
- configure
- configure.in
- include/click/packet.hh
- lib/llvmutils.cc
There is an issue with the reordering pass when we use -O3, but I will fix it soon.
> Disassemble/Inline AllAnno Struct

- elements/tcpudp/shifter.cc
- elements/tcpudp/shifter.hh
- elements/tcpudp/synflood.cc
- elements/tcpudp/synflood.hh
Shifter: allows to shift packets' 5-tuple by a given offset.
SYNFlood: generates a TCP SYN-flood like packet stream to a given destination,
> Shifter and SYNFlood elements

- .gitignore
- config-userlevel.h.in
- configure
- configure.in
- elements/analysis/frommindump.cc
- elements/analysis/frommindump.hh
- elements/research/flowruleinstaller.cc
- elements/research/flowruleinstaller.hh
- elements/standard/pad.cc
- elements/standard/pad.hh
FlowRuleInstaller is now always compiled, but it will support the update action only when rte_flow_update is found in the DPDK rte_flow library.
And some other small dangling commits...
> NICBench fixes

- .github/workflows/ci.yml
- elements/userlevel/fromnetmapdevice.cc
- elements/userlevel/fromnetmapdevice.hh
- elements/userlevel/netmapinfo.cc
- elements/userlevel/netmapinfo.hh
- elements/userlevel/queuedevice.hh
- elements/userlevel/tonetmapdevice.cc
- elements/userlevel/tonetmapdevice.hh
- include/click/netmapdevice.hh
- include/click/packet.hh
- lib/flow.cc
- lib/netmapdevice.cc
- lib/packet.cc
A few recent updates broke things will the CI was actually ignoring
netmap.
Fixes #353
> Netmap: Fix compilation

- elements/flow/flowipmanagerimp.cc
- elements/flow/flowipmanagerimp.hh
- elements/flow/flowprint.cc
- elements/flow/flowprint.hh
- elements/flow/sfmaker.cc
- elements/flow/sfmaker.hh
- elements/flow/tcpreorder.cc
- include/click/flow/common.hh
- include/click/flow/flowelement.hh
- include/click/tcphelper.hh
- lib/flowelement.cc
- test/standard/SFMaker.clicktest
Fix the FCB release bug, and also add a test case with 2 TCP flows,
verifying the right ACKs are removed
Poke @hamidgh09
> SFMaker: fix FCB state bug + test case

- userlevel/click.cc
Signed-off-by: Georgios Katsikas <gkatsikas@ubitech.eu>
> update DPDK arguments when no huge pages are used

- elements/userlevel/todevice.cc
- elements/userlevel/todevice.hh
Signed-off-by: Georgios Katsikas <gkatsikas@ubitech.eu>
> packet count handler for ToDevice element

- elements/analysis/replay.cc
- elements/analysis/replay.hh
Fix compilation error of #370 but the CI still has a small issue I'll fix later
> Fix previous commit, use a better solution

- elements/flow/flowratelimiter.cc
- elements/flow/flowratelimiter.hh
- include/click/batchelement.hh
- include/click/flow/flowelement.hh
- include/click/packetbatch.hh
- include/click/tokenbucket.hh
By @MassimoGirondi  I guess? Or was it me?
> Add FlowRateLimiter element

- elements/analysis/consistencycheck.hh
> push_batch not properly ifdef'd, failing to build if batch is disabled

- lib/flowrulemanager.cc
- userlevel/dpdk/Makefile
- userlevel/rte_parse.mk
> Compatibility with DPDK 23.03

- configure
- configure.in
- deps.sh
https://github.com/tbarbette/fastclick/pull/new/PRban makes sense, I'll merge it here.
> Merge mainline PR

- elements/analysis/recordtimestamp.cc
- elements/analysis/recordtimestamp.hh
- elements/tcpudp/fastudpflows.cc
- elements/tcpudp/fastudpflows.hh
- elements/userlevel/todpdkdevice.hh
- include/click/dpdkdevice.hh
- lib/dpdkdevice.cc
- vendor/nicscheduler/methods/rss.cc
This gives a more precise timestamp. Even I think the way to go is to use hardware pacing.
> RecordTimestamp: Enable the use of callback

- configure
> fix llvm-config parsing mixing up lib names

- .github/workflows/ci.yml
Automatically mirror to our gitlab which has much more testing, and performance regression support in the future
> Auto mirror

- elements/test/packettest.cc
- include/click/packet.hh
- lib/dpdkdevice.cc
- lib/packet.cc
- test/standard/Duplicate-dpdk-02.clicktest
Fix Packet::duplicate that was erroneous with --enable-dpdk-packet
> Finally fixing the CI
